Clientes/Clientes/Models/ClientesContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace Clientes.Models
{
    public class ClientesContext : DbContext
    {
        public ClientesContext(DbContextOptions<ClientesContext> options) : base(options)
        {
        }

        public DbSet<Customers> Customers { get; set; }
    }
}

Clientes/Clientes/Models/Customers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Clientes.Models
{
    public class Customers
    {
        [Key]
        public int Cid { get; set; }

        [Required(ErrorMessage = "Ingresa el Nombre del cliente")]
        [Display(Name = "Nombre del cliente")]
        public string Cname { get; set; }

        [Required(ErrorMessage = "Ingresa el email del cliente")]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Ingresa un email válido")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Edad del cliente")]
        [Display(Name = "Edad")]
        [Range(20, 50)]
        public int Age { get; set; }

        [Required(ErrorMessage = "Ingresa el monto de apertura")]
        [Display(Name = "Monto de apertura")]
        public int Saldo{ get; set; }
    }
}

Clientes/Clientes/Models/ErrorViewModel.cs
using System;

namespace Clientes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Clientes/Clientes/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Clientes.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Clientes.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ClientesContext _context;

        public CustomersController(ClientesContext context)
        {
            _context = context;


        }

        [HttpGet]
        public async Task<IActionResult> Index(string empsearch)
        {
            ViewData["GetEmployeeDetails"] = empsearch;
            var empquery = from x in _context.Customers select x;

            if (!String.IsNullOrEmpty(empsearch))
            {
                empquery = empquery.Where(x => x.Cname.Contains(empsearch) ||
                x.Email.Contains(empsearch));
            }

            return View(await empquery.AsNoTracking().ToListAsync());
        }

        public IActionResult Index()
        {
            var displaydata = _context.Customers.ToList();
            return View(displaydata);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Customers nCliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(nCliente);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(nCliente);
        }

        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var getDetail = await _context.Customers.FindAsync(id);

            return View(getDetail);
        }

        public async Task<IActionResult> Actualizar(int? id)
        {
            if (id==null)
            {
                return RedirectToAction("Index");
            }

            var getEmpDetail = await _context.Customers.FindAsync(id);

            return View(getEmpDetail);

        }

        [HttpPost]
        public async Task<IActionResult> Actualizar(Customers actualCustomer)
        {
            if(ModelState.IsValid)
            {
                _context.Update(actualCustomer);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(actualCustomer);

        }

        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var getEmpDetail = await _context.Customers.FindAsync(id);

            return View(getEmpDetail);
        }

        [HttpPost]
        public async Task<IActionResult> Eliminar(int id)
        {
            var getEmpdetail = await _context.Customers.FindAsync(id);
            _context.Customers.Remove(getEmpdetail);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Clientes/Clientes/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Clientes.Models;

namespace Clientes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Clientes/Clientes/Views/Customers/Actualizar.cshtml
@model Clientes.Models.Customers

@{
    ViewData["Title"] = "Actualizar";
}

<h1>Actualizar</h1>

<h4>Customers</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Actualizar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cid" class="control-label"></label>
                <input asp-for="Cid" class="form-control" readonly/>
                <span asp-validation-for="Cid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cname" class="control-label"></label>
                <input asp-for="Cname" class="form-control" />
                <span asp-validation-for="Cname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Saldo" class="control-label"></label>
                <input asp-for="Saldo" class="form-control" />
                <span asp-validation-for="Saldo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Clientes/Clientes/Views/Customers/Create.cshtml
@model Clientes.Models.Customers

@{
    ViewData["Title"] = "Create";
}

<h1>Cliente Nuevo</h1>

<h4>Datos del Cliente</h4>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cname" class="control-label"></label>
                <input asp-for="Cname" class="form-control" />
                <span asp-validation-for="Cname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Saldo" class="control-label"></label>
                <input asp-for="Saldo" class="form-control" />
                <span asp-validation-for="Saldo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresa al inicio</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Clientes/Clientes/Views/Customers/Detail.cshtml
@model Clientes.Models.Customers

@{
    ViewData["Title"] = "Detail";
}

<h1>Detalle del Cliente</h1>

<div>
    <h4>Customers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Saldo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Saldo)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Cid}) |
    <a asp-action="Index">Back to List</a>
</div>

Clientes/Clientes/Views/Customers/Eliminar.cshtml
@model Clientes.Models.Customers

@{
    ViewData["Title"] = "Eliminar";
}

<h1>Eliminar</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customers</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Saldo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Saldo)
        </dd>
    </dl>
    
    <form asp-action="Eliminar">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Clientes/Clientes/Views/Customers/Index.cshtml
@model IEnumerable<Clientes.Models.Customers>

@{
    ViewData["Title"] = "Index";
}

<h1>Inicio</h1>
<br />

<p>
    <a asp-action="Create">Ingresa un Cliente Nuevo</a>
</p>

<form asp-action="Index" method="get">

    <p>
        <i class="fa fa-search"></i>
        <input type="search" name="empsearch" placeholder="Ingresa nombre o email" value="@ViewData["GetEmployeesDetails"]" style="width:500px" />
        <input type="submit" name="Buscar" class="btn btn-primary">
        <a asp-action="Index">Ver Todos</a>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Saldo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Cid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Saldo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Actualizar", new { id = item.Cid }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Details", "Detail", new {id = item.Cid }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Delete", "Eliminar", new { id =item.Cid }, new { @class = "btn btn-danger" })
            </td>
        </tr>
}
    </tbody>
</table>

Clientes/Clientes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Clientes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Clientes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Home</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Clientes 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>